name: Terraform Deploy

on:
  push:
    branches:
      - main
      - '**'

env:
  TF_VERSION: '1.12.2'
  AWS_REGION: 'us-east-1'
  IMAGE_NAME: 'terraform_ecr_repo'
  DOCKER_TAG: 'latest'

jobs:
  terraform:
    if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-ci]'))
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Terraform environment variables
        run: |
          echo "TF_VAR_project_url=https://github.com/${{ github.repository }}" >> $GITHUB_ENV

      - name: Set environment for prod (main branch)
        run: echo "TF_VAR_environment=prod" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Set environment for dev (other branches)
        run: echo "TF_VAR_environment=dev" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'

      - name: Terraform Init
        working-directory: ./env
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: ./env
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./env
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./env
        run: terraform plan -input=false

#      - name: Terraform Apply
#        working-directory: ./env
#        run: terraform apply -auto-approve

#      - name: Extract ECR Repository URL from Terraform Output
#        id: tf_output
#        working-directory: ./env
#        run: |
#          REPO_URL=$(terraform output -raw ecr_repository_url)
#          echo "ECR_REPOSITORY_URL=$REPO_URL" >> $GITHUB_ENV

#      - name: Login to Amazon ECR
#        run: |
#          aws ecr get-login-password --region $AWS_REGION | \
#          docker login --username AWS --password-stdin $ECR_REPOSITORY_URL

#      - name: Build Docker image
#        run: |
#          docker build -t $IMAGE_NAME:$DOCKER_TAG .

#      - name: Tag Docker image with ECR repo URI
#        run: |
#          docker tag $IMAGE_NAME:$DOCKER_TAG $ECR_REPOSITORY_URL:$DOCKER_TAG

#      - name: Push Docker image to ECR
#        run: |
#          docker push $ECR_REPOSITORY_URL:$DOCKER_TAG
